version: '3.8'

services:
  web:
    ports:
      - "8000:8000"
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres-data:  